FROM ros:jazzy
RUN apt update -y && apt install ros-jazzy-turtlesim* -y
RUN apt update -y && apt install -y ros-jazzy-rqt-graph
RUN apt update -y && apt install -y wget
RUN apt update -y && apt install -y ros-jazzy-urdf-tutorial
RUN apt update -y && apt install -y liburdfdom-tools
RUN apt update -y && apt install -y ros-jazzy-ros-gz
RUN apt update -y && apt install -y ros-jazzy-navigation2 \
                                    ros-jazzy-nav2-bringup ros-jazzy-cartographer \
                                    ros-jazzy-cartographer-ros
RUN apt update -y && apt install -y ros-jazzy-slam-toolbox    
ENV TURTLEBOT3_MODEL=waffle                            
WORKDIR /root/ros_workspace
                                             