robot3/slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
 
    use_sim_time: true
    autostart: true
    odom_frame: robot3/odom
    base_frame: robot3/base_footprint
    map_frame: robot3/map
    map_name: /robot3/map
    use_map_saver: true
    scan_topic: scan
 
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.05
    map_update_interval: 2.0
    max_laser_range: 3.5
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0

    # --- NUOVI PARAMETRI DI AGGIORNAMENTO ODOMETRIA ---
    # Evitano che il robot aggiorni la mappa se è fermo o ruota impercettibilmente (causa di "sfocature")
    minimum_travel_distance: 0.2     # Aggiorna la mappa solo dopo 20 cm di spostamento
    minimum_travel_heading: 0.2      # Aggiorna la mappa solo dopo circa 11 gradi di rotazione
    
    # --- FIDUCIA NELL'ODOMETRIA ---
    # Limita l'area di ricerca del laser. Dato che in Gazebo le ruote non slittano, 
    # diciamo allo SLAM di cercare corrispondenze solo in un raggio di 30 cm dalla posizione stimata.
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.05
    
    # --- STRETTA SUI LOOP CLOSURE ---
    do_loop_closure: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0  
    
    # Alziamo le soglie di certezza. Lo SLAM chiuderà un loop (correggerà la mappa) 
    # SOLO se è estremamente sicuro che la stanza sia la stessa, ignorando i finti corridoi.
    loop_match_minimum_response_coarse: 0.50  # (Aumentato da 0.35)
    loop_match_minimum_response_fine: 0.65    # (Aumentato da 0.45)
    
    resolution: 0.05
